/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClienteleRouteImport } from './routes/clientele'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services_.$slug'
import { Route as ServicesSlugSubRouteImport } from './routes/services_.$slug_.$sub'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteleRoute = ClienteleRouteImport.update({
  id: '/clientele',
  path: '/clientele',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services_/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugSubRoute = ServicesSlugSubRouteImport.update({
  id: '/services_/$slug_/$sub',
  path: '/services/$slug/$sub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clientele': typeof ClienteleRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/$slug/$sub': typeof ServicesSlugSubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clientele': typeof ClienteleRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/$slug/$sub': typeof ServicesSlugSubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clientele': typeof ClienteleRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/services_/$slug': typeof ServicesSlugRoute
  '/services_/$slug_/$sub': typeof ServicesSlugSubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clientele'
    | '/contact'
    | '/services'
    | '/services/$slug'
    | '/services/$slug/$sub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clientele'
    | '/contact'
    | '/services'
    | '/services/$slug'
    | '/services/$slug/$sub'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clientele'
    | '/contact'
    | '/services'
    | '/services_/$slug'
    | '/services_/$slug_/$sub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClienteleRoute: typeof ClienteleRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesSlugSubRoute: typeof ServicesSlugSubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientele': {
      id: '/clientele'
      path: '/clientele'
      fullPath: '/clientele'
      preLoaderRoute: typeof ClienteleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$slug': {
      id: '/services_/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$slug_/$sub': {
      id: '/services_/$slug_/$sub'
      path: '/services/$slug/$sub'
      fullPath: '/services/$slug/$sub'
      preLoaderRoute: typeof ServicesSlugSubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClienteleRoute: ClienteleRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesSlugSubRoute: ServicesSlugSubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
