/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClienteleRouteImport } from './routes/clientele'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ServicesSlugIndexRouteImport } from './routes/services.$slug.index'
import { Route as ServicesSlugSubRouteImport } from './routes/services.$slug.$sub'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteleRoute = ClienteleRouteImport.update({
  id: '/clientele',
  path: '/clientele',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugIndexRoute = ServicesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesSlugRoute,
} as any)
const ServicesSlugSubRoute = ServicesSlugSubRouteImport.update({
  id: '/$sub',
  path: '/$sub',
  getParentRoute: () => ServicesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clientele': typeof ClienteleRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/$slug': typeof ServicesSlugRouteWithChildren
  '/services/': typeof ServicesIndexRoute
  '/services/$slug/$sub': typeof ServicesSlugSubRoute
  '/services/$slug/': typeof ServicesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clientele': typeof ClienteleRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesIndexRoute
  '/services/$slug/$sub': typeof ServicesSlugSubRoute
  '/services/$slug': typeof ServicesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clientele': typeof ClienteleRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/$slug': typeof ServicesSlugRouteWithChildren
  '/services/': typeof ServicesIndexRoute
  '/services/$slug/$sub': typeof ServicesSlugSubRoute
  '/services/$slug/': typeof ServicesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clientele'
    | '/contact'
    | '/services'
    | '/services/$slug'
    | '/services/'
    | '/services/$slug/$sub'
    | '/services/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clientele'
    | '/contact'
    | '/services'
    | '/services/$slug/$sub'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clientele'
    | '/contact'
    | '/services'
    | '/services/$slug'
    | '/services/'
    | '/services/$slug/$sub'
    | '/services/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClienteleRoute: typeof ClienteleRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientele': {
      id: '/clientele'
      path: '/clientele'
      fullPath: '/clientele'
      preLoaderRoute: typeof ClienteleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug/': {
      id: '/services/$slug/'
      path: '/'
      fullPath: '/services/$slug/'
      preLoaderRoute: typeof ServicesSlugIndexRouteImport
      parentRoute: typeof ServicesSlugRoute
    }
    '/services/$slug/$sub': {
      id: '/services/$slug/$sub'
      path: '/$sub'
      fullPath: '/services/$slug/$sub'
      preLoaderRoute: typeof ServicesSlugSubRouteImport
      parentRoute: typeof ServicesSlugRoute
    }
  }
}

interface ServicesSlugRouteChildren {
  ServicesSlugSubRoute: typeof ServicesSlugSubRoute
  ServicesSlugIndexRoute: typeof ServicesSlugIndexRoute
}

const ServicesSlugRouteChildren: ServicesSlugRouteChildren = {
  ServicesSlugSubRoute: ServicesSlugSubRoute,
  ServicesSlugIndexRoute: ServicesSlugIndexRoute,
}

const ServicesSlugRouteWithChildren = ServicesSlugRoute._addFileChildren(
  ServicesSlugRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRouteWithChildren
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRouteWithChildren,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClienteleRoute: ClienteleRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
